#!/bin/bash

TEMP_COUNT_FILE=".git/ai_lines_count.tmp"
TEMP_MANUAL_FILE=".git/manual_lines_count.tmp"
rm -f "$TEMP_COUNT_FILE"
rm -f "$TEMP_MANUAL_FILE"

total_ai_lines=0
total_manual_lines=0

staged_files=$(git diff --cached --name-only)

for file in $staged_files; do
    if [ -f "$file" ]; then


        total_ai_lines=$((total_ai_lines + ai_lines))

        file_added_lines=$(git diff --cached -- "$file" | grep "^+" | grep -v "^+++" | wc -l | tr -d ' ')

        manual_lines=$((file_added_lines - ai_lines))
        if [ "$manual_lines" -lt 0 ]; then manual_lines=0; fi
        total_manual_lines=$((total_manual_lines + manual_lines))


        git add "$file"
    fi
done

echo "$total_ai_lines" > "$TEMP_COUNT_FILE"
echo "$total_manual_lines" > "$TEMP_MANUAL_FILE"

exit 0
